// <auto-generated />
using System;
using HubMi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HubMi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HubMiDbContext))]
    [Migration("20261004041723_MultiRowInnovationEmbedding")]
    partial class MultiRowInnovationEmbedding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HubMi.Domain.Innovations.Innovation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beneficiaries")
                        .HasColumnType("text")
                        .HasColumnName("beneficiaries");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<string>("DetailsPdfUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details_pdf_url");

                    b.Property<string>("DisseminationBadge")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dissemination_badge");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("LicenseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("license_url");

                    b.Property<string>("MaterialsUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("materials_url");

                    b.Property<string>("Problems")
                        .HasColumnType("text")
                        .HasColumnName("problems");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("text")
                        .HasColumnName("target_group");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_innovation");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_innovation_category_id");

                    b.ToTable("innovation", (string)null);
                });

            modelBuilder.Entity("HubMi.Domain.Innovations.InnovationCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_innovation_category");

                    b.ToTable("innovation_category", (string)null);
                });

            modelBuilder.Entity("HubMi.Domain.Matching.MatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_key");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<bool>("Dictated")
                        .HasColumnType("boolean")
                        .HasColumnName("dictated");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ResolvedCategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_category_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<int>("TopPercent")
                        .HasColumnType("integer")
                        .HasColumnName("top_percent");

                    b.HasKey("Id")
                        .HasName("pk_match_request");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_match_request_received_at");

                    b.HasIndex("ResolvedCategoryId")
                        .HasDatabaseName("ix_match_request_resolved_category_id");

                    b.ToTable("match_request", (string)null);
                });

            modelBuilder.Entity("HubMi.Domain.Matching.MatchRequestResult", b =>
                {
                    b.Property<Guid>("MatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_request_id");

                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uuid")
                        .HasColumnName("innovation_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<int>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("MatchRequestId", "InnovationId")
                        .HasName("pk_match_request_result");

                    b.HasIndex("InnovationId")
                        .HasDatabaseName("ix_match_request_result_innovation_id");

                    b.ToTable("match_request_result", (string)null);
                });

            modelBuilder.Entity("HubMi.Infrastructure.Persistence.InnovationEmbedding", b =>
                {
                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uuid")
                        .HasColumnName("innovation_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("text_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("vector");

                    b.HasKey("InnovationId", "Kind", "Ordinal")
                        .HasName("pk_innovation_embedding");

                    b.ToTable("innovation_embedding", (string)null);
                });

            modelBuilder.Entity("HubMi.Domain.Innovations.Innovation", b =>
                {
                    b.HasOne("HubMi.Domain.Innovations.InnovationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_innovation_innovation_category_category_id");
                });

            modelBuilder.Entity("HubMi.Domain.Matching.MatchRequest", b =>
                {
                    b.HasOne("HubMi.Domain.Innovations.InnovationCategory", null)
                        .WithMany()
                        .HasForeignKey("ResolvedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_match_request_innovation_category_resolved_category_id");
                });

            modelBuilder.Entity("HubMi.Domain.Matching.MatchRequestResult", b =>
                {
                    b.HasOne("HubMi.Domain.Innovations.Innovation", null)
                        .WithMany()
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_request_result_innovation_innovation_id");

                    b.HasOne("HubMi.Domain.Matching.MatchRequest", null)
                        .WithMany("Results")
                        .HasForeignKey("MatchRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_request_result_match_request_match_request_id");
                });

            modelBuilder.Entity("HubMi.Infrastructure.Persistence.InnovationEmbedding", b =>
                {
                    b.HasOne("HubMi.Domain.Innovations.Innovation", null)
                        .WithMany()
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_innovation_embedding_innovation_innovation_id");
                });

            modelBuilder.Entity("HubMi.Domain.Matching.MatchRequest", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
